---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, nfsv3 
summary: Essas limitações conhecidas são específicas do Cloud Volumes ONTAP no Microsoft Azure. 
---
= Limitações conhecidas no Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As seguintes limitações conhecidas são específicas do Cloud Volumes ONTAP no Microsoft Azure. Certifique-se de também rever link:reference-limitations.html["Limitações em todos os provedores de nuvem"].



== Limitações com o uso de extensões Azure VM

O Cloud Volumes ONTAP não oferece suporte a extensões de máquina virtual (VM) do Azure e aplicativos de VM em uma implantação. O uso do Cloud Volumes ONTAP no Azure com extensões de VM causa atrasos nas operações e a NetApp recomenda evitá-las.



== Novas implantações não são suportadas

Novas implantações do Cloud Volumes ONTAP 9,6 não são mais suportadas no Azure. Você precisará implantar o Cloud Volumes ONTAP 9,7.



== Limitações DE HA

As limitações a seguir afetam os pares de HA do Cloud Volumes ONTAP no Microsoft Azure:

* NFSv4 não é suportado. NFSv3 é suportado.
* Pares HA não são suportados em algumas regiões.
+
https://bluexp.netapp.com/cloud-volumes-global-regions["Consulte a lista de regiões do Azure suportadas"^]


